### ISSUE TITLE
Negativa Pengar

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/Monopoly-Remastered#2]
Det är möjligt att få ett negativt antal pengar genom att slutföra en trade där man lovar mer pengar än vad man äger.
![image](https://github.com/EdwardKN/Monopoly-Remastered/assets/82646131/bdef7399-fba8-490d-a42c-17e9cabc9e8f)

**Comment by EndyMc** [comment]
Kan dessutom fortsätta att slå tärning och ge turen till nästa spelare trots att jag egentligen är bankrutt.

**Comment by EdwardKN** [comment]
Fixat i #1
